---
title: "Seasonality"
author: "David Su"
output:
  html_document:
    df_print: paged
---
Libraries used in this project:
```{r setup}
library(forecast, quietly=TRUE) # silently imports the library
library(stats)
rm(list=ls()) # removes previous variables
```

<!-- Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*. -->

<!-- When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file). -->

<!-- The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed. -->

Import the data
```{r import_csv}
csv<-read.csv('rawdata.csv', header = TRUE)
names(csv)=c('date','unemp')
head(csv)
```

Select data starting from the last NBER recession, i.e. December 2017.
```{r}
head(csv[-(1:167),])
```
Construct the time series object and plot it
```{r}
UnEmp=ts(csv$unemp[-(1:167)],start=c(2007,12),freq=12)
plot(UnEmp)
```

Seasonality model
```{r}
seas=tslm(UnEmp~season)
(s_seas=summary(seas))
```
```{r}
seas_factors=seas$coef
seas_factors[1]=0 # throw out the intercept
names(seas_factors)[1]='season1'
plot(seas_factors, type='l', lwd=2,
     xlab="Month", ylab='Seasonal Factors',
     main="Plot of Seasonal Factors")
```
Plot the residuals
```{r}
hist(seas$res,main='Histogram of Residuals',col='grey')
plot(seas$res)

```


# Fiddle
```{r}
d_UnEmp=UnEmp-lag(UnEmp,-1)
d_UnEmp
plot(d_UnEmp,
     xlab='Year',
     ylab='Change in Unemployment, p.p.',
     main='Monthly Changes in Unemployment')
```


```{r}
log_UnEmp=log(UnEmp)
plot(log_UnEmp)
plot(log_UnEmp-lag(log_UnEmp,-1))
```


```{r non-linear}
adj_t=time(UnEmp)-2008
nltrend=nls(UnEmp~a*exp(-k*adj_t)+b*adj_t+c*adj_t**2+f,
    start=c(a=-10,k=1,b=-1,c=0,f=20))
s_nltrend=summary(nltrend)
print(s_nltrend)
# residual plot
plot(s_nltrend$res,type='l')

trend_res=ts(s_nltrend$res,start=c(2007,12),freq=12)
trend_fitted=UnEmp-trend_res

plot(UnEmp)
lines(trend_fitted,col='red')

# seasonal model on the residuals of trend
seas_on_res=tslm(trend_res~season)
s_seas_on_res=summary(seas_on_res)
print(s_seas_on_res)

# residuals of seasonal model
plot(s_seas_on_res$res)


plot(UnEmp)
lines(trend_fitted+seas_on_res$fitted.values,col='red')
```

